Traceback (most recent call last):
  File "/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/microdf/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
mdf.gini(base.aftertax_income, base.s006)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m<ipython-input-13-5e7f39efca7b>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mmdf[0m[0;34m.[0m[0mgini[0m[0;34m([0m[0mbase[0m[0;34m.[0m[0maftertax_income[0m[0;34m,[0m [0mbase[0m[0;34m.[0m[0ms006[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/work/microdf/microdf/microdf/inequality.py[0m in [0;36mgini[0;34m(df, col, w, negatives)[0m
[1;32m     21[0m     """
[1;32m     22[0m     [0;31m# Requires float numpy arrays (not pandas Series or lists) to work.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 23[0;31m     [0mx[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0mdf[0m[0;34m[[0m[0mcol[0m[0;34m][0m[0;34m)[0m[0;34m.[0m[0mastype[0m[0;34m([0m[0;34m"float"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     24[0m     [0;32mif[0m [0mnegatives[0m [0;34m==[0m [0;34m"zero"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     25[0m         [0mx[0m[0;34m[[0m[0mx[0m [0;34m<[0m [0;36m0[0m[0;34m][0m [0;34m=[0m [0;36m0[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/pandas/core/series.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m    906[0m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_get_values[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    907[0m [0;34m[0m[0m
[0;32m--> 908[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_get_with[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    909[0m [0;34m[0m[0m
[1;32m    910[0m     [0;32mdef[0m [0m_get_with[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/pandas/core/series.py[0m in [0;36m_get_with[0;34m(self, key)[0m
[1;32m    946[0m [0;34m[0m[0m
[1;32m    947[0m         [0;31m# handle the dup indexing case GH#4246[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 948[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mloc[0m[0;34m[[0m[0mkey[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    949[0m [0;34m[0m[0m
[1;32m    950[0m     [0;32mdef[0m [0m_get_values_tuple[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/pandas/core/indexing.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m    877[0m [0;34m[0m[0m
[1;32m    878[0m             [0mmaybe_callable[0m [0;34m=[0m [0mcom[0m[0;34m.[0m[0mapply_if_callable[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mobj[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 879[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_getitem_axis[0m[0;34m([0m[0mmaybe_callable[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    880[0m [0;34m[0m[0m
[1;32m    881[0m     [0;32mdef[0m [0m_is_scalar_access[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m:[0m [0mTuple[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/pandas/core/indexing.py[0m in [0;36m_getitem_axis[0;34m(self, key, axis)[0m
[1;32m   1097[0m                     [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34m"Cannot index with multidimensional key"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1098[0m [0;34m[0m[0m
[0;32m-> 1099[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_getitem_iterable[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1100[0m [0;34m[0m[0m
[1;32m   1101[0m             [0;31m# nested tuple slicing[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/pandas/core/indexing.py[0m in [0;36m_getitem_iterable[0;34m(self, key, axis)[0m
[1;32m   1035[0m [0;34m[0m[0m
[1;32m   1036[0m         [0;31m# A collection of keys[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1037[0;31m         [0mkeyarr[0m[0;34m,[0m [0mindexer[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_get_listlike_indexer[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m,[0m [0mraise_missing[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1038[0m         return self.obj._reindex_with_indexers(
[1;32m   1039[0m             [0;34m{[0m[0maxis[0m[0;34m:[0m [0;34m[[0m[0mkeyarr[0m[0;34m,[0m [0mindexer[0m[0;34m][0m[0;34m}[0m[0;34m,[0m [0mcopy[0m[0;34m=[0m[0;32mTrue[0m[0;34m,[0m [0mallow_dups[0m[0;34m=[0m[0;32mTrue[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/pandas/core/indexing.py[0m in [0;36m_get_listlike_indexer[0;34m(self, key, axis, raise_missing)[0m
[1;32m   1252[0m             [0mkeyarr[0m[0;34m,[0m [0mindexer[0m[0;34m,[0m [0mnew_indexer[0m [0;34m=[0m [0max[0m[0;34m.[0m[0m_reindex_non_unique[0m[0;34m([0m[0mkeyarr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1253[0m [0;34m[0m[0m
[0;32m-> 1254[0;31m         [0mself[0m[0;34m.[0m[0m_validate_read_indexer[0m[0;34m([0m[0mkeyarr[0m[0;34m,[0m [0mindexer[0m[0;34m,[0m [0maxis[0m[0;34m,[0m [0mraise_missing[0m[0;34m=[0m[0mraise_missing[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1255[0m         [0;32mreturn[0m [0mkeyarr[0m[0;34m,[0m [0mindexer[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1256[0m [0;34m[0m[0m

[0;32m/usr/share/miniconda/envs/microdf/lib/python3.7/site-packages/pandas/core/indexing.py[0m in [0;36m_validate_read_indexer[0;34m(self, key, indexer, axis, raise_missing)[0m
[1;32m   1314[0m                 [0;32mwith[0m [0moption_context[0m[0;34m([0m[0;34m"display.max_seq_items"[0m[0;34m,[0m [0;36m10[0m[0;34m,[0m [0;34m"display.width"[0m[0;34m,[0m [0;36m80[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1315[0m                     raise KeyError(
[0;32m-> 1316[0;31m                         [0;34m"Passing list-likes to .loc or [] with any missing labels "[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1317[0m                         [0;34m"is no longer supported. "[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1318[0m                         [0;34mf"The following labels were missing: {not_found}. "[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Float64Index([ 280.6, 216.81, 268.85, 224.88,  240.8,\n              ...\n              268.69, 127.27, 119.75, 104.67, 104.67],\n             dtype='float64', name='RECID', length=277209). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"
KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Float64Index([ 280.6, 216.81, 268.85, 224.88,  240.8,\n              ...\n              268.69, 127.27, 119.75, 104.67, 104.67],\n             dtype='float64', name='RECID', length=277209). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

